'use strict';
(() => {
const $=id=>document.getElementById(id), C={fire:'#ff9367',water:'#6cdbd0',acid:'#a4ca65',gold:'#dfcb95'};
if(!window.LEVEL_DATA||!window.GameEngine){$('load-error').classList.remove('hidden');return;}
const levels=window.LEVEL_DATA,ctx=$('game').getContext('2d'),hero=$('hero').getContext('2d'),keys=new Set();
let world=null,current=0,screen='menu',paused=false,last=0,acc=0,records={},audio=null,sound=false,lastStatus='',message='';
try{records=JSON.parse(localStorage.getItem('ember-tide-v1')||'{}');}catch{}
function tone(f=400,len=.12){if(!sound)return;try{audio||=(new (window.AudioContext||window.webkitAudioContext)());audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(f*1.4,audio.currentTime+len);g.gain.setValueAtTime(.07,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+len);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+len);}catch{}}
function show(id){screen=id;keys.clear();document.querySelectorAll('.screen').forEach(e=>e.classList.toggle('hidden',e.id!==id));if(id==='levels')cards();}
function cards(){$('level-grid').replaceChildren();levels.forEach((l,i)=>{const b=document.createElement('button');b.className='level-card';const r=records[l.id];b.innerHTML=`<span class="num">${String(l.id).padStart(2,'0')}</span><span class="card-arrow">↗</span><h3>${l.name}</h3><p>${['Основы','Стихии','Плита','Рычаги','Ящик','Подъёмник','Синхронизация','На время','Три механизма','Финальное испытание'][i]}</p><div class="stars">${r?'★'.repeat(r.stars)+'☆'.repeat(3-r.stars):'☆☆☆'}</div><p>${r?'Рекорд: '+format(r.time):'Ещё не пройден'}</p>`;b.onclick=()=>start(i);$('level-grid').append(b);});}
function format(t){return String(Math.floor(t/60)).padStart(2,'0')+':'+String(Math.floor(t%60)).padStart(2,'0');}
function start(i){current=i;world=new GameEngine.World(levels[i]);paused=false;acc=0;lastStatus='play';show('play');$('overlay').classList.add('hidden');$('level-name').textContent=world.name;$('level-number').textContent='ИСПЫТАНИЕ '+String(i+1).padStart(2,'0')+' / 10';$('hint').textContent=world.subtitle;$('game').focus();tone(330);}
function modal(eye,title,text,buttons){$('overlay-eyebrow').textContent=eye;$('overlay-title').textContent=title;$('overlay-text').textContent=text;$('overlay-actions').replaceChildren();for(const [label,fn,primary] of buttons){const b=document.createElement('button');b.textContent=label;b.className=primary?'primary':'secondary';b.onclick=fn;$('overlay-actions').append(b);}$('overlay').classList.remove('hidden');keys.clear();}
function pause(){if(screen!=='play'||world.status!=='play')return;paused=!paused;keys.clear();if(paused)modal('СДЕЛАЕМ ПЕРЕДЫШКУ','Пауза','Храм подождёт. Продолжите, когда оба игрока будут готовы.',[['Продолжить',pause,true],['Выбор уровней',()=>show('levels')],['Главное меню',()=>show('menu')]]);else{$('overlay').classList.add('hidden');$('game').focus();}}
function outcome(){if(world.status===lastStatus)return;lastStatus=world.status;if(world.status==='dead'){tone(110,.2);modal('ПОПЫТОК СКОЛЬКО УГОДНО','Попробуем ещё?','Одна стихия погасла. Начните вместе и найдите другой путь.',[['Ещё попытка',()=>start(current),true],['Выбор уровней',()=>show('levels')]]);}if(world.status==='win'){const stars=world.collected===world.gems.length?3:world.time<90?2:1,old=records[world.id];records[world.id]={time:Math.min(old?.time??Infinity,world.time),stars:Math.max(old?.stars??0,stars)};try{localStorage.setItem('ember-tide-v1',JSON.stringify(records));}catch{}tone(700,.3);modal('★'.repeat(stars)+'☆'.repeat(3-stars),current===9?'Храм пробуждён!':'Равновесие найдено',`${format(world.time)} · Кристаллы ${world.collected}/${world.gems.length}. ${current===9?'Вы прошли все испытания и вернули храму свет.':'Ваш путь продолжается.'}`,[[current===9?'Все уровни':'Следующий уровень',()=>current===9?show('levels'):start(current+1),true],['Пройти ещё раз',()=>start(current)],['Меню',()=>show('menu')]]);}}
$('start').onclick=()=>{const next=levels.findIndex(l=>!records[l.id]);start(next<0?0:next);};$('select').onclick=()=>show('levels');$('how').onclick=()=>show('help');$('help-start').onclick=()=>start(0);$('restart').onclick=()=>start(current);$('pause').onclick=pause;$('brand').onclick=e=>{e.preventDefault();show('menu');};document.querySelectorAll('.menu-back').forEach(b=>b.onclick=()=>show('menu'));$('sound').onclick=()=>{sound=!sound;$('sound').textContent='Звук: '+(sound?'вкл.':'выкл.');tone();};
window.addEventListener('keydown',e=>{if(screen==='play'&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','KeyW','KeyA','KeyD','KeyE','Escape','KeyR'].includes(e.code)){e.preventDefault();if(!e.repeat&&e.code==='Escape')pause();if(!e.repeat&&e.code==='KeyR')start(current);keys.add(e.code);}});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();if(screen==='play'&&!paused&&world.status==='play')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys.clear();if(screen==='play'&&!paused&&world.status==='play')pause();}});
function round(c,x,y,w,h,r=6){c.beginPath();c.roundRect(x,y,w,h,r);c.fill();}
function diamond(c,x,y,size,color){c.fillStyle=color;c.beginPath();c.moveTo(x,y-size);c.lineTo(x+size*.7,y);c.lineTo(x,y+size);c.lineTo(x-size*.7,y);c.closePath();c.fill();}
function glow(c,x,y,r,color){let g=c.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,color);g.addColorStop(1,'transparent');c.fillStyle=g;c.fillRect(x-r,y-r,2*r,2*r);}
function character(c,x,y,type,scale=1,t=0,moving=false){c.save();c.translate(x,y);c.scale(scale,scale);const col=C[type];glow(c,14,20,65,type==='fire'?'#ff93671a':'#6cdbd01a');c.fillStyle='#0004';c.beginPath();c.ellipse(14,40,18,4,0,0,Math.PI*2);c.fill();c.fillStyle=col;c.beginPath();if(type==='fire'){c.moveTo(1,28);c.quadraticCurveTo(-1,12,10,7);c.quadraticCurveTo(12,-3,20,-8+Math.sin(t*4)*2);c.quadraticCurveTo(17,9,25,14);c.quadraticCurveTo(36,32,25,36);c.quadraticCurveTo(12,41,1,28);}else{c.moveTo(14,-3);c.bezierCurveTo(10,8,-2,16,1,28);c.bezierCurveTo(2,42,27,42,29,28);c.bezierCurveTo(32,18,18,7,14,-3);}c.fill();c.fillStyle=type==='fire'?'#ffd7a0':'#bef8e6';c.beginPath();c.ellipse(14,27,10,9,0,0,Math.PI*2);c.fill();c.fillStyle='#182c32';round(c,7,21,4,6,2);round(c,19,21,4,6,2);c.strokeStyle='#182c32';c.lineWidth=1.5;c.beginPath();c.arc(15,28,3,0,Math.PI);c.stroke();c.fillStyle=col;const walk=moving?Math.sin(t*17)*3:0;round(c,3,34,9,6+walk,3);round(c,18,34,9,6-walk,3);c.restore();}
function background(c,w,h,t){c.fillStyle='#102229';c.fillRect(0,0,w,h);glow(c,w*.6,h*.22,w*.65,'#38695435');c.strokeStyle='#39534645';c.lineWidth=2;for(let x=75;x<w;x+=175){c.fillStyle='#172d32';round(c,x,110,56,h-110,4);c.fillStyle='#233b3c';round(c,x-8,106,72,14,2);c.strokeRect(x+10,130,36,h-130);c.strokeStyle='#38514855';c.beginPath();c.moveTo(x+28,148);c.lineTo(x+28,380);c.stroke();}c.strokeStyle='#38514866';for(let y=150;y<h;y+=90){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke();}for(let i=0;i<30;i++){const x=(i*127.3)%w,y=((i*91+t*(4+i%5))%(h-90));c.fillStyle=i%3?'#bfceaa30':'#6cdbd03b';c.beginPath();c.arc(x,y,1+i%2,0,7);c.fill();}c.strokeStyle='#78988122';c.lineWidth=1;c.beginPath();c.arc(w/2,h*.45,h*.34,Math.PI,Math.PI*2);c.stroke();}
function terrain(c,p){c.fillStyle='#243a3d';round(c,p.x,p.y,p.w,p.h,2);c.fillStyle='#4a6560';c.fillRect(p.x,p.y,p.w,9);c.fillStyle='#85937a';c.fillRect(p.x,p.y,p.w,2);c.strokeStyle='#172c31';c.lineWidth=2;for(let y=p.y+36;y<720;y+=42){c.beginPath();c.moveTo(p.x,y);c.lineTo(p.x+p.w,y);c.stroke();for(let x=p.x+(y%84?40:0);x<p.x+p.w;x+=90){c.beginPath();c.moveTo(x,y);c.lineTo(x,y+42);c.stroke();}}for(let x=p.x+7;x<p.x+p.w;x+=31){c.fillStyle='#5f805c';c.fillRect(x,p.y+3,18,3+(x%4));}}
function portal(c,e,t){const col=C[e.type];glow(c,e.x+e.w/2,e.y+e.h*.5,70,e.type==='fire'?'#ff936724':'#6cdbd028');c.fillStyle='#20393c';round(c,e.x-5,e.y-5,e.w+10,e.h+5,16);c.fillStyle='#0d2229';round(c,e.x,e.y,e.w,e.h,15);c.strokeStyle=col;c.lineWidth=2;c.beginPath();c.roundRect(e.x,e.y,e.w,e.h,15);c.stroke();c.globalAlpha=.4+.2*Math.sin(t*3);c.fillStyle=col;round(c,e.x+7,e.y+8,e.w-14,e.h-12,10);c.globalAlpha=1;diamond(c,e.x+e.w/2,e.y+23,5,col);}
function render(t){background(ctx,1200,720,t);for(const p of world.platforms)terrain(ctx,p);for(const h of world.hazards){glow(ctx,h.x+h.w/2,h.y+3,h.w,C[h.type]+'16');ctx.fillStyle=C[h.type];ctx.beginPath();ctx.moveTo(h.x,h.y+5);for(let x=h.x;x<=h.x+h.w;x+=4)ctx.lineTo(x,h.y+3+Math.sin(x*.09+t*4)*2);ctx.lineTo(h.x+h.w,h.y+h.h);ctx.lineTo(h.x,h.y+h.h);ctx.fill();ctx.fillStyle='#ffffff40';for(let x=h.x+10;x<h.x+h.w;x+=26)ctx.fillRect(x,h.y+8,9,1);}
for(const l of world.lifts){ctx.strokeStyle='#82937655';ctx.setLineDash([4,9]);ctx.beginPath();ctx.moveTo(l.x+l.w/2,l.high);ctx.lineTo(l.x+l.w/2,l.low+18);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#8e9d7d';round(ctx,l.x,l.y,l.w,l.h,4);ctx.fillStyle='#d4cb95';ctx.fillRect(l.x+5,l.y,l.w-10,3);}
for(const e of world.exits)portal(ctx,e,t);
for(const g of world.gates){ctx.fillStyle='#344b45';ctx.fillRect(g.x-5,0,5,g.h);ctx.fillRect(g.x+g.w,0,5,g.h);ctx.globalAlpha=g.open?.12:1;ctx.fillStyle='#8fac80';round(ctx,g.x,g.open?g.h-10:0,g.w,g.open?10:g.h,2);if(!g.open){ctx.strokeStyle='#d6d5a0';ctx.lineWidth=1;for(let y=30;y<g.h;y+=38){ctx.beginPath();ctx.moveTo(g.x+3,y);ctx.lineTo(g.x+g.w-3,y+15);ctx.moveTo(g.x+3,y+15);ctx.lineTo(g.x+g.w-3,y);ctx.stroke();}}ctx.globalAlpha=1;}
for(const s of world.switches){const on=world.signals[s.id],col=C[s.type]||C.gold;ctx.fillStyle=on?'#7bccaa':'#344847';if(s.kind==='plate'){round(ctx,s.x,s.y,s.w,s.h,3);ctx.strokeStyle=col;ctx.lineWidth=2;ctx.strokeRect(s.x+12,s.y-15,24,11);if(s.type==='crate'){ctx.fillStyle=col;ctx.fillRect(s.x+19,s.y-12,10,5);}else {ctx.fillStyle=col;ctx.beginPath();ctx.arc(s.x+24,s.y-9,3,0,7);ctx.fill();}if(s.group){ctx.fillStyle=C.gold;ctx.font='15px system-ui';ctx.fillText('∞',s.x+18,s.y-24);}}else{round(ctx,s.x,s.y+29,s.w,21,4);ctx.strokeStyle=on?'#87deb7':col;ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(s.x+13,s.y+34);ctx.lineTo(s.x+(on?23:3),s.y+8);ctx.stroke();ctx.fillStyle=col;ctx.beginPath();ctx.arc(s.x+(on?23:3),s.y+8,5,0,7);ctx.fill();ctx.font='12px system-ui';ctx.textAlign='center';ctx.fillText(s.duration?(world.timers[s.id]?Math.ceil(world.timers[s.id])+'с':'12с'):(s.type==='fire'?'E':s.type==='water'?'↓':'E / ↓'),s.x+13,s.y-8);ctx.textAlign='left';}}
for(const c of world.crates){ctx.fillStyle='#9b845c';round(ctx,c.x,c.y,c.w,c.h,3);ctx.strokeStyle='#d1b97f';ctx.lineWidth=2;ctx.strokeRect(c.x+4,c.y+4,c.w-8,c.h-8);ctx.beginPath();ctx.moveTo(c.x+5,c.y+5);ctx.lineTo(c.x+c.w-5,c.y+c.h-5);ctx.moveTo(c.x+c.w-5,c.y+5);ctx.lineTo(c.x+5,c.y+c.h-5);ctx.stroke();}
for(const g of world.gems)if(!g.taken){const y=g.y+Math.sin(t*3+g.x)*4;glow(ctx,g.x,y,35,C[g.type]+'24');diamond(ctx,g.x,y,11,C[g.type]);ctx.strokeStyle='#fff9';ctx.beginPath();ctx.moveTo(g.x,y-7);ctx.lineTo(g.x-4,y);ctx.stroke();}
world.players.forEach(p=>character(ctx,p.x,p.y,p.type,1,t,!!p.vx));ctx.fillStyle='#b0c3b277';ctx.font='10px system-ui';ctx.fillText('ИСКРА',world.spawn[0].x-4,world.spawn[0].y-28);ctx.fillText('КАПЛЯ',world.spawn[1].x-4,world.spawn[1].y-28);$('time').textContent=format(world.time);$('gems').textContent='◈ '+world.collected+' / '+world.gems.length;}
function renderHero(t){background(hero,640,520,t);hero.save();hero.translate(320,200);hero.strokeStyle='#8ca79166';hero.lineWidth=2;hero.beginPath();hero.arc(0,0,138,0,Math.PI*2);hero.stroke();hero.beginPath();hero.arc(0,0,112,0,Math.PI*2);hero.stroke();for(let i=0;i<12;i++){const a=i*Math.PI/6;diamond(hero,Math.cos(a)*125,Math.sin(a)*125,4,'#aab99188');}diamond(hero,0,0,28,C.gold);hero.strokeStyle='#71938755';hero.beginPath();hero.moveTo(-80,0);hero.lineTo(80,0);hero.moveTo(0,-80);hero.lineTo(0,80);hero.stroke();hero.restore();terrain(hero,{x:0,y:435,w:230,h:85});terrain(hero,{x:230,y:400,w:200,h:120});terrain(hero,{x:430,y:435,w:210,h:85});glow(hero,185,325,140,'#ff936728');glow(hero,450,325,140,'#6cdbd028');character(hero,150,323+Math.sin(t*2)*2,'fire',2.7,t);character(hero,440,323+Math.sin(t*2+2)*2,'water',2.7,t);diamond(hero,85,355+Math.sin(t*3)*5,12,C.fire);diamond(hero,565,350+Math.sin(t*3+2)*5,12,C.water);hero.fillStyle='#98b5a58c';hero.font='10px system-ui';hero.letterSpacing='2px';hero.fillText('ИСКРА',159,300);hero.fillText('КАПЛЯ',445,300);}
function loop(now){const dt=Math.min(.1,(now-last)/1000||0);last=now;if(screen==='play'&&world){if(!paused&&world.status==='play'){acc+=dt;while(acc>=1/120){const old=world.collected;world.step(1/120,[{left:keys.has('KeyA'),right:keys.has('KeyD'),jump:keys.has('KeyW'),action:keys.has('KeyE')},{left:keys.has('ArrowLeft'),right:keys.has('ArrowRight'),jump:keys.has('ArrowUp'),action:keys.has('ArrowDown')}]);acc-=1/120;if(old<world.collected)tone(600);if(world.status!=='play'){acc=0;break;}}outcome();}render(now/1000);}else if(screen==='menu')renderHero(now/1000);requestAnimationFrame(loop);}requestAnimationFrame(loop);
window.gameDebug={start,get world(){return world;},levels,show,pause};
})();
